/* Descripción: Creación de los roles de seguridad solicitados para el proyecto.*/
-- ELIMINAR LOS ROLES SI YA EXISTEN

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_VENDEDOR';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_OPERARIO_BODEGA';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

CREATE ROLE ROL_VENDEDOR;
CREATE ROLE ROL_OPERARIO_BODEGA;

GRANT SELECT, INSERT, UPDATE ON Existencias TO ROL_OPERARIO_BODEGA;

GRANT SELECT, INSERT, UPDATE ON Inventarios TO ROL_OPERARIO_BODEGA;

GRANT SELECT ON Productos TO ROL_VENDEDOR;

SELECT *
FROM USER_ROLE_PRIVS;
-- PERMISOS DEL ROL VENDEDOR

GRANT CREATE SESSION TO ROL_VENDEDOR;

GRANT SELECT ON Clientes TO ROL_VENDEDOR;
GRANT SELECT ON Productos TO ROL_VENDEDOR;
GRANT SELECT ON Existencias TO ROL_VENDEDOR;

GRANT SELECT, INSERT, UPDATE
ON Facturas
TO ROL_VENDEDOR;

GRANT SELECT, INSERT, UPDATE
ON Detalle_Factura_Productos
TO ROL_VENDEDOR;

-- PERMISOS DEL OPERARIO DE BODEGA

GRANT CREATE SESSION TO ROL_OPERARIO_BODEGA;

GRANT SELECT
ON Productos
TO ROL_OPERARIO_BODEGA;

GRANT SELECT
ON Existencias
TO ROL_OPERARIO_BODEGA;

GRANT SELECT, INSERT, UPDATE
ON Inventarios
TO ROL_OPERARIO_BODEGA;

GRANT SELECT, INSERT, UPDATE
ON Detalle_Inventario
TO ROL_OPERARIO_BODEGA;

GRANT UPDATE
ON Existencias
TO ROL_OPERARIO_BODEGA;

-- PERMISOS DEL APROBADOR

/*GRANT CREATE SESSION TO ROL_APROBADOR;

GRANT SELECT
ON Inventarios
TO ROL_APROBADOR;

GRANT SELECT, UPDATE
ON Detalle_Inventario
TO ROL_APROBADOR;

GRANT SELECT, UPDATE
ON Solicitudes_Transporte
TO ROL_APROBADOR;

GRANT SELECT, UPDATE
ON Existencias
TO ROL_APROBADOR;*/
